# Configuration file for ObsidianDestroyer
# Set Regen, Frequency or any ExplosionSource to -1 if you want to disable. Will also make blocks unbreakable.
# DropChance is measured in percent. Default in Minecraft was 30 (%), but is based on the explosion strength now.

LiquidMultiplier: 2
BlastRadius: 3
DurabilityChecker: '392'
VoidProtector: true
Drops:
  DropChance: 0
  DontDrop:
  - '7'
Blocks:
  '49': 2
  '116': 2
  '130': 2
Regen:
  Frequency: 10
  Amount: 1
ExplosionSources:
  PrimedTnt: 1
